In [90]:
import numpy as np
import sys
sys.path.append("/Users/prabhatkumar/Library/CloudStorage/GoogleDrive-888prabhat@gmail.com/My Drive/Work/quantitative_research/")

In [2]:
actual = np.array([1,0,0,1,2,0,0,1,2,0,0,1])
preds = np.array([0,0,0,1,1,0,0,1,2,0,0,2])

In [4]:
x = np.where(actual == 0)

In [5]:
x[0]

array([ 1,  2,  5,  6,  9, 10])

In [9]:
index = np.argwhere(actual==0)
actual_1 = np.delete(actual, index)
preds_1 = np.delete(preds, index)

In [10]:
actual_1

array([1, 1, 2, 1, 2, 1])

In [11]:
preds_1

array([0, 1, 1, 1, 2, 2])

In [15]:
import sklearn.metrics as mt
tn, fp, fn, tp = mt.confusion_matrix(actual, preds).ravel()


ValueError: not enough values to unpack (expected 4, got 3)

In [23]:
mt.confusion_matrix(actual, preds)

array([[6, 0, 0],
       [1, 2, 1],
       [0, 1, 1]])

In [19]:
def calculate_confusion_matrix(y_true, y_pred):
    classes = list(set(y_true))
    n_classes = len(classes)
    
    tp = [0] * n_classes
    fn = [0] * n_classes
    fp = [0] * n_classes
    tn = [0] * n_classes
    
    for i, cls in enumerate(classes):
        for j in range(len(y_true)):
            if y_true[j] == cls and y_pred[j] == cls:
                tp[i] += 1
            elif y_true[j] == cls and y_pred[j] != cls:
                fn[i] += 1
            elif y_true[j] != cls and y_pred[j] == cls:
                fp[i] += 1
            else:
                tn[i] += 1
    
    return tp, fn, fp, tn

In [20]:
tp, fn, fp, tn = calculate_confusion_matrix(actual, preds)

In [22]:
actual,preds

(array([1, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1]),
 array([0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 0, 2]))

In [21]:
tp, fn, fp, tn

([6, 2, 1], [0, 2, 1], [1, 1, 1], [5, 7, 9])

In [24]:
mt.confusion_matrix(actual, preds)

array([[6, 0, 0],
       [1, 2, 1],
       [0, 1, 1]])

In [26]:
tn, fp, fn, tp = mt.confusion_matrix(actual, preds)


ValueError: not enough values to unpack (expected 4, got 3)

In [27]:
from scipy.special import expit
y_pred = expit(preds).astype(int)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
def calculate_accuracy_minority_classes(y_true, y_pred):
    from collections import Counter

    class_counts = Counter(y_true)
    majority_class = class_counts.most_common(1)[0][0]
    
    correct_count = 0
    total_count = 0
    for i in range(len(y_true)):
        if y_true[i] != majority_class:
            total_count += 1
            if y_true[i] == y_pred[i]:
                correct_count += 1
    
    accuracy = correct_count / total_count
    return accuracy

In [46]:
actual = np.array([1,0,0,1,2,0,0,1,2,0,0,2,1,1,1,1,1])
preds = np.array([1,0,1,1,2,0,0,1,2,0,0,2,1,0,0,0,0])

In [47]:
acc = calculate_accuracy_minority_classes(actual, preds)
acc

0.8888888888888888

In [62]:
import numpy as np

def calculate_accuracy_minority_classes(y_true, y_pred):
    unique, counts = np.unique(y_true, return_counts=True)
    if unique.size > 2:
        average="weighted"
    else:
        average="binary"
    majority_class = unique[np.argmax(counts)]
    
    mask = y_true != majority_class
    y_true_minority = y_true[mask]
    y_pred_minority = y_pred[mask]
    
    accuracy = np.mean(y_true_minority == y_pred_minority)
    f1 = mt.f1_score(y_true_minority,y_pred_minority,average=average)
    print(accuracy,f1)
    return accuracy

In [63]:
acc = calculate_accuracy_minority_classes(actual, preds)
acc

0.8888888888888888 0.9393939393939392


0.8888888888888888

In [50]:
unique, counts = np.unique(actual, return_counts=True)
majority_class = unique[np.argmax(counts)]
majority_class

1

In [59]:
unique.size

3

In [58]:
counts

array([6, 8, 3])

In [64]:
def confusion_matrix(actual, predicted, classes):
    num_classes = len(classes)
    confusion_matrix = [[0] * num_classes for _ in range(num_classes)]
    for i, actual_class in enumerate(actual):
        predicted_class = predicted[i]
        confusion_matrix[actual_class][predicted_class] += 1
    TP = [0] * num_classes
    FN = [0] * num_classes
    FP = [0] * num_classes
    TN = [0] * num_classes
    for i in range(num_classes):
        for j in range(num_classes):
            if i == j:
                TP[i] += confusion_matrix[i][j]
                for k in range(num_classes):
                    if k != i:
                        TN[i] += confusion_matrix[k][j]
            else:
                FN[i] += confusion_matrix[i][j]
                FP[j] += confusion_matrix[i][j]
    return TP, FN, FP, TN

In [65]:
TP, FN, FP, TN = confusion_matrix(actual, preds, classes=[0,1,2])

In [66]:
TP

[5, 4, 3]

In [77]:
def calculate_confusion_matrix(y_true, y_pred):
    classes = list(set(y_true))
    n_classes = len(classes)
    
    tp = [0] * n_classes
    fn = [0] * n_classes
    fp = [0] * n_classes
    tn = [0] * n_classes
    
    for i, cls in enumerate(classes):
        for j in range(len(y_true)):
            if y_true[j] == cls and y_pred[j] == cls:
                tp[i] += 1
            elif y_true[j] == cls and y_pred[j] != cls:
                fn[i] += 1
            elif y_true[j] != cls and y_pred[j] == cls:
                fp[i] += 1
            else:
                tn[i] += 1
    
    return np.sum(tp), np.sum(fn), np.sum(fp), np.sum(tn)

In [86]:
def gini(actual, pred, cmpcol=0, sortcol=1):
    assert (len(actual) == len(pred))
    all = np.asarray(np.c_[actual, pred, np.arange(len(actual))], dtype=float)
    all = all[np.lexsort((all[:, 2], -1 * all[:, 1]))]
    totalLosses = all[:, 0].sum()
    giniSum = all[:, 0].cumsum().sum() / totalLosses

    giniSum -= (len(actual) + 1) / 2.
    return giniSum / len(actual)

In [87]:
actual = np.array([1,0,0,1,2,0,0,1,2,0,0,2,1,1,1,1,1])
preds = np.array([1,0,1,1,2,0,0,1,2,0,0,2,1,0,0,0,0])

In [88]:
v = gini(actual, preds)
v

0.11344537815126052

In [82]:
TP1, FN1, FP1, TN1 = calculate_confusion_matrix(actual, preds)

In [83]:
TP1, FN1, FP1, TN1

(12, 5, 5, 29)

In [75]:
TN1

[7, 8, 14]

In [72]:
mt.confusion_matrix(actual, preds)


array([[5, 1, 0],
       [4, 4, 0],
       [0, 0, 3]])

In [101]:
from modelling.metrics import metrics as met
loss = met.calculate_profit_cost_for_all_class(actual, preds,tp_w=3,fn_w=2,fp_w=2,tn_w=0)

In [102]:
loss

16

In [115]:
actual = np.array([1,0,0,1,2,0,0,1,2,0,0,2,1,1,1,1,1,3,3,3])
preds =  np.array([1,0,1,1,1,2,0,1,2,0,0,2,1,2,0,0,0,3,1,3])

In [116]:
loss = met.calculate_profit_cost_for_minority_class(actual, preds,tp_w=3,fn_w=4,fp_w=4,tn_w=0)
loss

4

In [117]:
loss = met.calculate_gini_for_minority_class(actual, preds)
loss

0.1805555555555555

In [118]:
loss = met.calculate_gini_for_all_class(actual, preds)
loss

0.11630434782608692

In [119]:
a = (np.array([-0.07115496, -0.05986183, -0.04515969, -0.06518066,
       -0.07547638, -0.03610574]), np.array([-0.08702217, -0.11358481, -0.13911354, -0.07945196,
       -0.06996478, -0.13757402]), np.array([-0.07637147, -0.10370852, -0.14546257, -0.10412843,
       -0.10246049, -0.12143681]))

In [166]:
a = ['test1','test2']
s = "','".join(a)
print(f"('{s}')")

('test1','test2')


In [143]:
expit(a[1])

array([0.47825818, 0.47163429, 0.46527759, 0.48014745, 0.48251594,
       0.46566064])

In [157]:
set(expit(a[2]))

{0.4636983449180312,
 0.4696780512372228,
 0.4739913886167275,
 0.47409608321136426,
 0.4744072632868366,
 0.48091640718100925}

In [140]:
y_pred = expit([-0.07115496, -0.05986183, -0.04515969, -0.06518066,
       -0.07547638, 2000000])

In [159]:
c = np.array([[2.],
 [2.],
 [2.]])
c.squeeze()

array([2., 2., 2.])

In [149]:
expit(a).argmax(axis=0)

array([0, 0, 0, 0, 1, 0])

In [150]:
a.argmax(axis=0)

AttributeError: 'tuple' object has no attribute 'argmax'

In [153]:
np.array(a).argmax(axis=0)

array([0, 0, 0, 0, 1, 0])

In [156]:
expit(a).max(axis=0)

array([0.48221876, 0.48503901, 0.488712  , 0.4837106 , 0.48251594,
       0.49097455])